const PDFDocument = require('pdfkit');

const generateReceiptPDF = (appointment, payment, res) => {
  const doc = new PDFDocument({ margin: 50 });

  // Stream directly to Express response
  doc.pipe(res);

  // Add Receipt Header
  doc.fontSize(20).text('Receipt / Payment Confirmation', { align: 'center' });
  doc.moveDown();
  
  doc.fontSize(12).text(`Transaction ID: ${payment.transactionId}`);
  doc.text(`Date: ${new Date(payment.createdAt).toLocaleDateString()}`);
  doc.text(`Payment Status: ${payment.status.toUpperCase()}`);
  doc.moveDown();

  doc.text('--------------------------------------------------');
  doc.moveDown();

  // Add Appointment info
  doc.text(`Appointment ID: ${appointment._id}`);
  doc.text(`Patient: ${appointment.patient.name}`);
  doc.text(`Doctor: ${appointment.doctor.user.name}`);
  doc.text(`Date: ${new Date(appointment.date).toLocaleDateString()}`);
  doc.text(`Time Slot: ${appointment.slot}`);
  doc.text(`Type: ${appointment.consultationType.toUpperCase()}`);
  doc.moveDown();

  doc.text('--------------------------------------------------');
  doc.moveDown();

  // Price
  doc.fontSize(14).text(`Total Amount Paid: $${payment.amount}`, { bold: true });
  doc.moveDown();
  doc.fontSize(10).text('Thank you for choosing HealthTracker Pro.', { align: 'center', italic: true });

  doc.end();
};

const generatePrescriptionPDF = (appointment, res) => {
  const doc = new PDFDocument({ margin: 50 });

  doc.pipe(res);

  // Prescription Header
  doc.fontSize(24).text('PRESCRIPTION', { align: 'center', color: '#dc3545' });
  doc.moveDown();

  // Clinic / Doctor info
  doc.fontSize(12).text(`Doctor: Dr. ${appointment.doctor.user.name}`);
  doc.text(`Specialization: ${appointment.doctor.specialization}`);
  doc.text(`Hospital: ${appointment.doctor.hospital}`);
  doc.moveDown();

  doc.text('--------------------------------------------------');
  doc.moveDown();

  // Patient info
  doc.text(`Patient Name: ${appointment.patient.name}`);
  doc.text(`Gender: ${appointment.patient.gender || 'N/A'}`);
  doc.text(`Age/DOB: ${appointment.patient.dob ? new Date(appointment.patient.dob).toLocaleDateString() : 'N/A'}`);
  doc.text(`Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown();

  doc.text('--------------------------------------------------');
  doc.moveDown();

  // Rx symbol
  doc.fontSize(16).text('Rx:', { bold: true });
  doc.moveDown();

  // Medicines list
  doc.fontSize(12);
  if (appointment.prescription && appointment.prescription.medicines.length > 0) {
    appointment.prescription.medicines.forEach((med, index) => {
      doc.text(`${index + 1}. ${med.name} - ${med.dosage} (${med.duration})`);
      if (med.instructions) {
        doc.fontSize(10).text(`   Instructions: ${med.instructions}`).fontSize(12);
      }
      doc.moveDown(0.5);
    });
  } else {
    doc.text('No medicines prescribed.');
  }

  doc.moveDown();
  if (appointment.prescription && appointment.prescription.notes) {
    doc.text(`Notes: ${appointment.prescription.notes}`);
  }

  doc.moveDown(2);
  doc.fontSize(10).text('Generated by HealthTracker Pro digital portal.', { align: 'center', italic: true });

  doc.end();
};

module.exports = {
  generateReceiptPDF,
  generatePrescriptionPDF
};
